SRC_PREFIX=src/
BIN_PREFIX=bin/
LIBS_PREFIX=.libs/
OBJS_PREFIX=.objs/

CC=g++

CFLAGS=-g -Wall -Wextra -std=c++14 -O2

LLVMFLAGS=`llvm-config-5.0 --cxxflags --ldflags --system-libs --libs core`

all: $(BIN_PREFIX)compiler

LEXER_SRC_PREFIX=$(SRC_PREFIX)lexer/
LEXER_SRC=$(shell find $(LEXER_SRC_PREFIX) -maxdepth 1 -name '*.cpp')
LEXER_OBJS_PREFIX=$(OBJS_PREFIX)lexer/
LEXER_OBJS=$(patsubst $(LEXER_SRC_PREFIX)%.cpp,$(LEXER_OBJS_PREFIX)%.o,$(LEXER_SRC))
LEXER_LIB_PREFIX=$(LIBS_PREFIX)lexer/
LEXER_LIB=$(LEXER_LIB_PREFIX)lexer.a

$(LEXER_LIB): $(LEXER_OBJS)
	mkdir -p $(LEXER_LIB_PREFIX)
	ar rcs $@ $^

$(LEXER_OBJS_PREFIX)%.o: $(LEXER_SRC_PREFIX)%.cpp $(LEXER_SRC_PREFIX)%.hpp
	mkdir -p $(LEXER_OBJS_PREFIX)
	$(CC) $(CFLAGS) -c $< -o $@

PARSER_SRC_PREFIX=$(SRC_PREFIX)parser/
PARSER_SRC=$(shell find $(PARSER_SRC_PREFIX) -maxdepth 1 -name '*.cpp')
PARSER_OBJS_PREFIX=$(OBJS_PREFIX)parser/
PARSER_OBJS=$(patsubst $(PARSER_SRC_PREFIX)%.cpp,$(PARSER_OBJS_PREFIX)%.o,$(PARSER_SRC))
PARSER_LIB_PREFIX=$(LIBS_PREFIX)parser/
PARSER_LIB=$(PARSER_LIB_PREFIX)parser.a

$(PARSER_LIB): $(PARSER_OBJS)
	mkdir -p $(PARSER_LIB_PREFIX)
	ar rcs $@ $^

$(PARSER_OBJS_PREFIX)%.o: $(PARSER_SRC_PREFIX)%.cpp $(PARSER_SRC_PREFIX)%.hpp
	mkdir -p $(PARSER_OBJS_PREFIX)
	$(CC) $(CFLAGS) -I$(LEXER_SRC_PREFIX) -c $< -o $@

CODEGEN_SRC_PREFIX=$(SRC_PREFIX)codegen/
CODEGEN_SRC=$(shell find $(CODEGEN_SRC_PREFIX) -maxdepth 1 -name '*.cpp')
CODEGEN_OBJS_PREFIX=$(OBJS_PREFIX)codegen/
CODEGEN_OBJS=$(patsubst $(CODEGEN_SRC_PREFIX)%.cpp,$(CODEGEN_OBJS_PREFIX)%.o,$(CODEGEN_SRC))
CODEGEN_LIB_PREFIX=$(LIBS_PREFIX)codegen/
CODEGEN_LIB=$(CODEGEN_LIB_PREFIX)codegen.a

$(CODEGEN_LIB): $(CODEGEN_OBJS)
	mkdir -p $(CODEGEN_LIB_PREFIX)
	ar rcs $@ $^

$(CODEGEN_OBJS_PREFIX)%.o: $(CODEGEN_SRC_PREFIX)%.cpp $(CODEGEN_SRC_PREFIX)%.hpp
	mkdir -p $(CODEGEN_OBJS_PREFIX)
	$(CC) $(CFLAGS) $(LLVMFLAGS) -I$(LEXER_SRC_PREFIX) -I$(PARSER_SRC_PREFIX) -c $< -o $@

COMPILER_SRC_PREFIX=$(SRC_PREFIX)
COMPILER_SRC=$(shell find $(COMPILER_SRC_PREFIX) -maxdepth 1 -name '*.cpp')
COMPILER_OBJS_PREFIX=$(OBJS_PREFIX)
COMPILER_OBJS=$(patsubst $(COMPILER_SRC_PREFIX)%.cpp,$(COMPILER_OBJS_PREFIX)%.o,$(COMPILER_SRC))
COMPILER_INCLUDES=-I$(LEXER_SRC_PREFIX) -I$(PARSER_SRC_PREFIX) -I$(CODEGEN_SRC_PREFIX)

$(BIN_PREFIX)compiler: $(COMPILER_OBJS) $(LEXER_LIB) $(PARSER_LIB) $(CODEGEN_LIB)
	mkdir -p $(BIN_PREFIX)
	$(CC) $(CFLAGS) $(LLVMFLAGS) $^ -o $@

$(COMPILER_OBJS_PREFIX)%.o: $(COMPILER_SRC_PREFIX)%.cpp
	mkdir -p $(COMPILER_OBJS_PREFIX)
	$(CC) $(CFLAGS) $(LLVMFLAGS) $(COMPILER_INCLUDES) -c $< -o $@

.PHONY: clean

clean:
	rm -rf $(BIN_PREFIX) $(OBJS_PREFIX) $(LIBS_PREFIX)

